# name: Pull from Amazon ECS

# on:
#   workflow_run:
#     workflows: [ "Push to Amazon ECS" ]
#     types:
#       - completed

# jobs:
#   build:
#     name: Pull the Docker Image
#     runs-on: [self-hosted, dev]
#     environment: production

#     steps:
#     - name: Configure AWS credentials
#         uses: aws-actions/configure-aws-credentials@v1
#         with:
#             aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#             aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#             aws-region: us-east-1
#         run: sudo docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
#     - name: Pull Docker image
#         run: sudo docker pull luoni/dabot-client:latest
#     - name: Run Docker Container and connect to dabot-devops_default
#         run: |-
#         sudo docker run -d -p 8080:8080 -p 443:443 \
#             --volume /Dabot/conf/nginx.conf.d:/etc/nginx/conf.d \
#             --volume /Dabot/conf/ssl:/etc/nginx/ssl \
#             --network dabot-devops_default \
#             --name dabot-client-container \
#             luoni/dabot-client
